services:
  react-app:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    # We don't override 'CMD' here because we already set it in the Dockerfile.
    # If we really want to, we could do:
    # command: npm run dev -- --host 0.0.0.0
